language: cpp

compiler:
 - gcc

before_install:
 # we need at least g++-4.8 for c++11 features
 - if [ "${CXX}" = 'g++' ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi;
 - sudo apt-get update -y
 # upgrade compilers
 - if [ "${CXX}" = 'g++' ]; then sudo apt-get install -y gcc-4.8 g++-4.8; fi;
 - sudo apt-get install -y make libboost-dev libboost-program-options-dev zlib1g-dev libbz2-dev libexpat1-dev libsparsehash-dev libprotobuf-dev protobuf-compiler libosmpbf-dev libboost-test-dev libgdal1-dev libgeos++-dev
 - cd examples
 - make

install:
 - true

#env:
#  - TESTS_TO_RUN=cpp BINDINGS=none CPP_TESTS=true BENCHMARK=true

before_script:
 - make test

script:
 - true

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#mapnik"
#    use_notice: true
#  email:
#    on_success: [never]
#    on_failure: [change]

