language: cpp

compiler:
 - gcc
 - clang

before_install:
 # we need at least g++-4.8 for c++11 features
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -y

install:
 # upgrade compilers
 - sudo apt-get install -y gcc-4.8 g++-4.8
 # upgrade libosmium dependencies
 - sudo apt-get install -y make libboost-dev libboost-program-options-dev zlib1g-dev libbz2-dev libexpat1-dev libsparsehash-dev libprotobuf-dev protobuf-compiler libosmpbf-dev libboost-test-dev libgdal1-dev libgeos++-dev libproj-dev
 - git clone https://github.com/scrosby/OSM-binary.git
 - cd OSM-binary/src
 - make
 - sudo make install
 - cd ../..

#env:

before_script:
 - true

script:
 - if [ "${CXX}" = 'g++' ]; then export CXX=g++-4.8; fi;
 - make test
 - cd examples
 - make

#notifications:
#  irc:
#    channels:
#      - ""
#    use_notice: true
#  email:
#    on_success: [never]
#    on_failure: [change]

