language: cpp

compiler:
 - gcc
 - clang

before_install:
 # we need at least g++-4.8 for c++11 features
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get update --yes --quiet

install:
 # upgrade compilers
 - sudo apt-get install --yes gcc-4.8 g++-4.8
 # make sure 'cpp' is the just installed current one
 - sudo rm /usr/bin/cpp
 - sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
 # upgrade libosmium dependencies
 - sudo apt-get install --yes make libboost-dev libboost-program-options-dev libsparsehash-dev libprotobuf-dev protobuf-compiler libgeos++-dev libproj-dev
 - sudo apt-get install --yes make libgdal1h libgdal-dev
 # OSMPBF is too old, install from git
 #- sudo apt-get install --yes libosmpbf-dev
 - git clone https://github.com/scrosby/OSM-binary.git
 - cd OSM-binary/src
 - make
 - sudo make install
 - cd ../..
 # install 'json' ruby module needed for multipolygon tests
 - /usr/bin/ruby /usr/bin/gem install json
 - /usr/bin/ruby /usr/bin/gem which json
 - /usr/bin/ruby /usr/bin/gem --version
 - ruby --version
 - /usr/bin/env ruby --version
 - /usr/bin/ruby --version

#env:

before_script:
 - true

script:
 - if [ "${CXX}" = 'g++' ]; then export CXX=g++-4.8; fi;
 - mkdir build
 - cd build
 - cmake -L -DCMAKE_BUILD_TYPE=Dev ..
 - make VERBOSE=1
 - ctest -V

after_failure:
 - cd build
 - cat test/osm-testdata/multipolygon.log
 - cat test/osm-testdata/compare-areas.log


