#
# Configuration for appveyor.com
#

environment:
  matrix:
  - configuration: Dev
#  - configuration: Release

# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2014 CTP4

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\libosmium

platform: x64

install:
  - ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"" amd64
  - patch -N -p1 < libosmium.diff
  - SET LODEPSDIR=c:\projects\libosmium\libosmium-deps
  - SET LIBBZIP2=%LODEPSDIR%\bzip2\lib\libbz2.lib
  - SET LIBBZIP2=%LIBBZIP2:\=/%
  - ps: Start-FileDownload https://mapnik.s3.amazonaws.com/dist/dev/libosmium-deps-win-14.0-x64.7z -FileName lodeps.7z
  - 7z x lodeps.7z > nul

build_script:
  - cd c:\projects\libosmium
  - mkdir build
  - cd build
  - call ..\cmake\build2.bat


