#
# Configuration for appveyor.com
#

environment:
  matrix:
  - configuration: Debug
  - configuration: Release

# branches to build
branches:
  # whitelist
  only:
    - develop

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\libosmium

platform: x64

install:
  # by default, all script lines are interpreted as batch
  - nuget install protobuf
  - cd c:\projects\libosmium
  - git clone https://github.com/osmcode/libosmium

build_script:
  - cd c:\projects\libosmium\libosmium
  - mkdir build
  - cd build
  - echo Running cmake...
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - SET P=c:/projects/libosmium/libosmium
  - cmake .. -G "Visual Studio 12 Win64" -DCMAKE_BUILD_TYPE=%Configuration% -DBZIP2_INCLUDE_DIR=%P%/libs/include -DBZIP2_LIBRARIES=%P%/libs/lib/libbz2.lib -DCMAKE_INSTALL_PREFIX=%P%/libs -DBOOST_ROOT=%P%/boost_min -DBoost_USE_STATIC_LIBS=ON -T CTP_Nov2013
  - msbuild /clp:Verbosity=minimal /nologo libosmium.sln
  - msbuild /clp:Verbosity=minimal /nologo tests.vcxproj

